---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgB+Dn4mNRPNFwcMlt5mJSLNfouJlJbTv6kEvVM5EvNz0QeXFjKbU+nZysY7YeOgsnvdb3VmTpePGUr5AMJ4+m+3ElxguWj2j7/aJDKPJSkIcD0rxikxXLWH0q5v5s1Yc4CCwmY558IR6i6IISngPbWqCJVYOEjHV23xc+jvSjwCMwI9SKHQbG1b8qsCrTEqgMzHjPR/O1s10R61gf92C/kU01Is8+X6aCfWr/UMrXPZ02XnlpB4J9YSSHmc99jFplERGSnWhLTXGB6Il9BEWtO6Xa9bXHknfQ3qYQD+tiS0DmXhZUHEDsqPV001YJUDz3V9g1YaPRt1jXFToWqm+Io11TsYP2ZMOzDltAa7cCTLD0zlxcVZK+a1O2xzsOqjkplsGEExUmoxDPYrF1p343P1b0tUAsVByduiFNFbo/yAaze6aKXHmA8G18AIeAP7d76kdqKZiXZH9q3PiLeH7Cv7Gip+DTSoHdQ3QKmJ2E1hEDhOZp4WCG54Q6OnUJuwy6KEbRYvRq7fmoNFFkILNpXY78FTyrJH8q1evUiE0ZL4uwdhT1vUXvuo8lECGJ3vhwfbP2rg6QH2AGlrl9D+PVhnDW0bpXukCcTDqLPT2QwvE38b/wKNUMMbLRjPMb+pCT4dr2SNdcg6KnGgH6kNDSpr4EGmMlHZeUWXTktXd00Z9m0g8PdfPwSd0RYZZpKJcdFVvG3J2BPgSaZ71q+0rFgw0FjAql6FwNI7
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database
